// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repositories} from '../models';

export function Create(arg1:repositories.MonthEvent):Promise<repositories.MonthEvent>;

export function Delete(arg1:repositories.MonthEvent):Promise<void>;

export function Read():Promise<Array<repositories.MonthEvent>>;

export function Update(arg1:repositories.MonthEvent):Promise<repositories.MonthEvent>;
