// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repositories} from '../models';

export function Create(arg1:repositories.Note):Promise<repositories.Note>;

export function Delete(arg1:repositories.Note):Promise<void>;

export function Read():Promise<Array<repositories.Note>>;

export function Update(arg1:repositories.Note):Promise<repositories.Note>;
