// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['repositories']['WeeklyCalendar']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['repositories']['WeeklyCalendar']['Delete'](arg1);
}

export function Read() {
  return window['go']['repositories']['WeeklyCalendar']['Read']();
}

export function Update(arg1) {
  return window['go']['repositories']['WeeklyCalendar']['Update'](arg1);
}
