// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsUpdateAvailable() {
  return window['go']['main']['App']['IsUpdateAvailable']();
}

export function Update() {
  return window['go']['main']['App']['Update']();
}
