// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function Create(arg1:main.Event):Promise<main.Event>;

export function Delete(arg1:number):Promise<void>;

export function Read():Promise<Array<main.Event>>;

export function Update(arg1:number,arg2:{[key: string]: any}):Promise<void>;
