// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['Calendar']['Close']();
}

export function Create(arg1) {
  return window['go']['main']['Calendar']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['Calendar']['Delete'](arg1);
}

export function Read() {
  return window['go']['main']['Calendar']['Read']();
}

export function Update(arg1, arg2) {
  return window['go']['main']['Calendar']['Update'](arg1, arg2);
}
