// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['MonthCalendar']['Close']();
}

export function Create(arg1) {
  return window['go']['main']['MonthCalendar']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['MonthCalendar']['Delete'](arg1);
}

export function Read() {
  return window['go']['main']['MonthCalendar']['Read']();
}

export function Update(arg1, arg2) {
  return window['go']['main']['MonthCalendar']['Update'](arg1, arg2);
}
