// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNotesFolder() {
  return window['go']['main']['NoteManager']['CreateNotesFolder']();
}
