name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: root dir
        run: |
          cd C:\
          dir
#      - name: Checkout
#        uses: actions/checkout@v2

#      - name: choco updage mingw
#        run: |
#          choco upgrade mingw --version=13.1

#      - name: Install MSYS2
#        uses: msys2/setup-msys2@v2
#        with:
#          msystem: MINGW64
#          update: true
#          install: mingw-w64-x86_64-toolchain
#
#      - name: msys2 gcc version
#        working-directory: C:\msys64\mingw64\bin
#        run: |
#          dir
#
#      - name: add to path
#        run: |
#          Add-Content $env:GITHUB_PATH "C:\msys64\mingw64\bin"

#      - name: add to path
#        run: |
#          setx PATH "%PATH%;C:\msys64\mingw64\bin"
          

#      - name: the global gcc version (supposed to match!!)
#        run: |
#          gcc -v


     
#
#      - name: Install Go
#        uses: actions/setup-go@v2.1.3
#        with:
#          go-version: 1.18
#      - name: Build with Go
#        run: |
#          go build -o app.exe testGCC.go

#      - name: Build with Go
#        run: |
#          go build -o app.exe testGCC.go


######################################################################

#name: Test GORM GCC
#
#on: [ push ]
#
#jobs:
#  build:
#    runs-on: windows-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Install Go
#        uses: actions/setup-go@v2.1.3
#        with:
#          go-version: 1.17.2
#
#      - name: Set up MSYS2
#        run: |
#          # Download MSYS2 installer
#          curl -L -o msys2-installer.exe https://github.com/msys2/msys2-installer/releases/latest/download/msys2-x86_64-latest.exe
#
#          # Install MSYS2 silently
#          ./msys2-installer.exe -d
#
#          # Initialize MSYS2
#          source ${{ runner.workspace }}/msys64/msys2_shell.cmd -mingw64 -defterm -no-start -here -l -c "echo Hello from MSYS2"
#
#      - name: Install GCC 64-bit
#        run: |
#          # Update MSYS2 package databases
#          pacman -Syu --noconfirm
#
#          # Install GCC 64-bit
#          pacman -S --noconfirm mingw-w64-x86_64-gcc
#
#          # Check the installed GCC version
#          g++ --version
#
#      - name: Build with Go
#        run: |
#          go build -o app.exe .
