name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Check GCC
        run: |
          gcc -v
      - name: Install MinGW
        run: |
          choco install mingw
      - name: Build with Go
        run: |
          // #cgo LDFLAGS: -lmsvcrt
          go build -o app.exe testGCC.go


#name: Test GORM GCC
#
#on: [ push ]
#
#jobs:
#  build:
#    runs-on: windows-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Install Go
#        uses: actions/setup-go@v2.1.3
#        with:
#          go-version: 1.17.2
#
#      - name: Set up MSYS2
#        run: |
#          # Download MSYS2 installer
#          curl -L -o msys2-installer.exe https://github.com/msys2/msys2-installer/releases/latest/download/msys2-x86_64-latest.exe
#
#          # Install MSYS2 silently
#          ./msys2-installer.exe -d
#
#          # Initialize MSYS2
#          source ${{ runner.workspace }}/msys64/msys2_shell.cmd -mingw64 -defterm -no-start -here -l -c "echo Hello from MSYS2"
#
#      - name: Install GCC 64-bit
#        run: |
#          # Update MSYS2 package databases
#          pacman -Syu --noconfirm
#
#          # Install GCC 64-bit
#          pacman -S --noconfirm mingw-w64-x86_64-gcc
#
#          # Check the installed GCC version
#          g++ --version
#
#      - name: Build with Go
#        run: |
#          go build -o app.exe .
